### ISSUE TITLE
Check out our paper on the matter

### ISSUE THREAD

**Issue by greshake** [velocitatem/raccoon#1]
We've been trying to get attention to our paper (https://github.com/greshake/llm-security) which presented these and more techniques, but it isn't getting much traction. Check it out, it's a step beyond what you've included so far in terms of demos and examples :)

**Comment by velocitatem** [comment]
I read your paper and found it very interesting! I would be interested in collaborating on combining some of our methods if you are open to it. What do you think?

**Comment by greshake** [comment]
Hell yea! Send me an email to papers@kai-greshake.de and get in touch.
